user  nginx;

events {
  worker_connections   1000;
}

http {
  resolver 127.0.0.11 valid=5s;
  server {
    listen 5000;
    location / {
      set $backend http://web:5000;
      proxy_pass $backend;
    }
  }
}
